development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: colgateinterndb@gmail.com
  :password: oak13drive
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: colgateinterndb@gmail.com
  :password: oak13drive
  :enable_starttls_auto: true

